### ISSUE TITLE
can resources load remote images url?

### ISSUE THREAD

**Issue by RandomCivil** [mfg92/hugo-shortcode-gallery#26]
hi,can resources load remote images url?

**Comment by mfg92** [comment]
Hi,
i am not sure if I understand your question correctly, but I would answer with "no".

**Comment by RandomCivil** [comment]
hi
my resources src is like

```yaml
---
title: "My First Post"
date: 2021-09-27T08:57:03+08:00
draft: true
albumthumb: "my-first-post/1.png"
resources:
- src: "my-first-post/images/1.png"
- src: "my-first-post/images/2.png"
- src: "https://static.theviper.xyz/images/nginx-ingress-load-balance.png"
---
```
