### ISSUE TITLE
Nothing appear

### ISSUE THREAD

**Issue by sp4d1n0** [mfg92/hugo-shortcode-gallery#32]
Hi! I'm trying to use your awesome shortcode, yet nothing appear on my side. The page resources appear in the build root, yet nothing shows where it should get the gallery. It's a multi language site, with hugo 0.89.4. I followed the instructions, so I have all my images under images/* and copied the shortcode command. No error at build or serve, yet no gallery... any clue?

**Comment by mfg92** [comment]
I need more input to help you with this issue. Can you create a zip file that contains all files needed to reproduce your issue.

**Comment by stiliajohny** [comment]
same here , 

here is my folder structure 
![Screenshot_2021-12-28-48_ | 500](https://user-images.githubusercontent.com/17669235/147608048-cfd0e3f6-790e-49d1-9012-22ebd2f7b3ae.png)

here is my config.toml
```toml
...
baseURL = "https://stiliajohny.github.io/"
# [en, zh-cn, fr, pl, ...] determines default content language
defaultContentLanguage = "en"
# theme
theme = ["LoveIt", "hugo-shortcode-gallery"]
# themes directory
# themesDir = "./themes"
...
```

here is the post that contains the gallery ( its the `index.en.md` )
```markdown 
---
title: ""
date: 2021-12-24
author: "John Stilia"

# resources:
# - name: featured-image
#   src: java-vurn.png
# - name: featured-image-preview
#   src: log4j-1.png

draft: false
lightgallery: true
fontawesome: true
linkToMarkdown: true
rssFullText: false

toc:
  auto: true
---

{{< gallery match="./images/*" sortOrder="desc" rowHeight="150"  previewType="blur" embedPreview="true" >}}

```
