### ISSUE TITLE
Featured image not being included in the gallery

### ISSUE THREAD

**Issue by geeklingo** [mfg92/hugo-shortcode-gallery#41]
I've noticed that if i use a featured image with the aether theme that this image is not included in the gallery. Is this by design? And is there a way to overwrite this behaviour?

![CleanShot 2022-04-28 at 08 21 52](https://user-images.githubusercontent.com/36504208/165641041-32123cba-61d1-4a03-bcad-ecfd041fe5f6.png)

![CleanShot 2022-04-28 at 08 22 01](https://user-images.githubusercontent.com/36504208/165641051-0b1dae3d-5bd6-46af-bd71-ad92265f25e2.png)

post:
```
---
title: "DSM Progress Week 1"
date: "2012-05-15"
categories: 
  - "aquatic"
tags: 
  - "algae"
  - "aquarium"
  - "dry-start-method"
  - "dsm"
  - "nano-tank"
  - "planted-tank"
resources:
  - name: featuredImage
    src: "images/tank18.jpg"
---

Progress shots at week 1:

{{< gallery match="images/*" sortOrder="desc" rowHeight="150" margins="5" thumbnailResizeOptions="600x600 q90 Lanczos" showExif=true previewType="blur" embedPreview="true" loadJQuery=true >}}
```
