### ISSUE TITLE
Change font color of filter buttons

### ISSUE THREAD

**Issue by maja-mielke** [mfg92/hugo-shortcode-gallery#43]
Hello,

I managed to include the gallery into my website and everything is working fine so far (thank you for the great work!).

However, I would like to change (darken) the font color of the filter buttons, as they currently appear with white font on light gray background on my website.

Any idea on how to achieve this?

I am very new to hugo, your help is much appreciated!

**Comment by mfg92** [comment]
You have to add a CSS rule like this to your site/theme:
```CSS
.justified-gallery-filterbar button {
	color: #000;
	border-color: #000;
}
```
With that rule in place, it looks like this on my website:
![grafik](https://user-images.githubusercontent.com/11365250/166717414-752ef84e-9292-40f4-8073-7de486d66441.png)
