### ISSUE TITLE
Gallery is not showing

### ISSUE THREAD

**Issue by Ianneee** [mfg92/hugo-shortcode-gallery#49]
Hello, unluckily the gallery isn't showing on my hugo site. I'm trying to use it in the homepage.
I'm using [beautiful hugo](https://github.com/halogenica/beautifulhugo) as theme.
Into hugo server i don't receive any error.
My `config.toml` is like:

```toml
baseURL = 'http://www. [...] .com'
languageCode = 'it'
DefaultContentLanguage = "it"
title = 'Title'
theme = ["beautifulhugo", "hugo-shortcode-gallery"]
metaDataFormat = "yaml"

[ ... theme configs after ... ]
```
Content folder is like this:
```
content/
├── images
│   ├── blue-fish.jpeg
│   ├── Cerbero.jpeg
│   ├── Eyes-scaled.jpeg
│   ├── Gohan.jpg
│   ├── jimi.jpeg
│   ├── Moth.jpeg
│   └── Viola-scaled.jpeg
├── _index.md
└── Punk-scaled.jpeg
```
This is my _index.md (also the home page)
```md
---
title: ""
date: 2022-09-18T23:15:47+02:00
draft: true
---
![imag](/images/Cerbero.jpeg)  <---- This image works correctly

{{< gallery match="images/*" sortOrder="desc" rowHeight="150" margins="5" thumbnailResizeOptions="600x600 q90 Lanczos" showExif=true previewType="blur" embedPreview="true" >}}
```

I've downloaded you repo as submodule into `themes`
```
themes/  [only folders]
├── beautifulhugo
│   ├── etc...
└── hugo-shortcode-gallery
    ├── assets
    │   └── shortcode-gallery
    │       └── font-awesome
    ├── layouts
    │   └── shortcodes
    └── static
        └── shortcode-gallery
            ├── justified_gallery
            ├── lazy
            └── swipebox
                ├── css
                ├── img
                └── js
```
